POST http://localhost:4000/getToken
Content-Type: application/json

{
    "username": "Luis"
}

###

POST http://localhost:4000/LogIn
Content-Type: application/json

{
    "email": "alanyeger23@gmail.com",
    "password": "12345678"
}

###

POST http://localhost:4000/LogOut
Content-Type: application/json

{
    "email": "alanyeger2@gmail.com",
    "password": "12121212"
}

###

DELETE  http://localhost:4000/DeleteUser
Content-Type: application/json

{
    "email": "borrar@gmail.com",
    "password": "12121212"
}

###

PUT  http://localhost:4000/UpdateUsername
Content-Type: application/json

{
    "name": "hola",
    "email": "alanyeger1@gmail.com",
    "password": "12345678"
}

###

POST http://localhost:4000/SignUp
Content-Type: application/json

{
    "name": "Alan",
    "email": "alanyeger24@gmail.com",
    "password": "12121212",
    "passwordConfirm": "12121212"
}

###

POST http://localhost:4000/SendEmail
Content-Type: application/json

{
    "email": "alanyeger1@gmail.com"
}

###

POST http://localhost:4000/python
Content-Type: application/json

{
    "email": "C:\Users\47129428\Documents\GitHub\Hawkeye\Videos Tenis para Analizar\y2mate.com - The Ultimate Clutch  shorts_1080pFHR.mp4"
}